<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Areas\Log\**" />
    <Compile Remove="Areas\Vendor\**" />
    <Content Remove="Areas\Log\**" />
    <Content Remove="Areas\Vendor\**" />
    <EmbeddedResource Remove="Areas\Log\**" />
    <EmbeddedResource Remove="Areas\Vendor\**" />
    <None Remove="Areas\Log\**" />
    <None Remove="Areas\Vendor\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Atlas.Core\Atlas.Core.csproj" />
    <ProjectReference Include="..\Atlas.Infrastructure\Atlas.Infrastructure.csproj" />
    <ProjectReference Include="..\Atlas.Services\Atlas.Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\Category\Controllers\" />
    <Folder Include="Areas\Category\Data\" />
    <Folder Include="Areas\Category\Models\" />
    <Folder Include="Areas\Category\Views\" />
    <Folder Include="Areas\HRM\Data\" />
    <Folder Include="Areas\HRM\Models\" />
    <Folder Include="Areas\HRM\Views\" />
    <Folder Include="Areas\Account\Data\" />
    <Folder Include="Areas\Party\Controllers\" />
    <Folder Include="Areas\Party\Data\" />
    <Folder Include="Areas\Party\Models\" />
    <Folder Include="Areas\Party\Views\" />
    <Folder Include="Areas\Purchase\Controllers\" />
    <Folder Include="Areas\Purchase\Data\" />
    <Folder Include="Areas\Purchase\Models\" />
    <Folder Include="Areas\Sale\Controllers\" />
    <Folder Include="Areas\Sale\Data\" />
    <Folder Include="Areas\Sale\Models\" />
    <Folder Include="Areas\Sale\Views\" />
    <Folder Include="Areas\Setting\Controllers\" />
    <Folder Include="Areas\Setting\Data\" />
    <Folder Include="Areas\Setting\Models\" />
    <Folder Include="Areas\Setting\Views\" />
    <Folder Include="Areas\Warehouse\Controllers\" />
    <Folder Include="Areas\Warehouse\Models\" />
    <Folder Include="Areas\Warehouse\Views\" />
  </ItemGroup>

</Project>
